config/routes.rb
Fub::Application.routes.draw do
  resources :wallets

  root 'wallets#new'

  get '*path' => redirect('/')

end

app/models/wallet.rb
require 'file_size_validator' 
class Wallet < ActiveRecord::Base
	mount_uploader :file, FileUploader
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
  before_action :set_wallet, only: [:show, :edit, :update, :destroy]

  # GET /wallets
  # GET /wallets.json
  def index
    @wallets = Wallet.all
  end

  # GET /wallets/1
  # GET /wallets/1.json
  def show
  end

  # GET /wallets/new
  def new
    @wallet = Wallet.new
  end

  # GET /wallets/1/edit
  def edit
  end

  # POST /wallets
  # POST /wallets.json
  def create
    @wallet = Wallet.new(wallet_params)

    respond_to do |format|
      if @wallet.save
        format.html { redirect_to root_url, notice: 'Thank you for your donation.' }
        format.json { render action: 'show', status: :created, location: @wallet }
      else
        format.html { render action: 'new' }
        format.json { render json: @wallet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wallets/1
  # PATCH/PUT /wallets/1.json
  def update
    respond_to do |format|
      if @wallet.update(wallet_params)
        format.html { redirect_to @wallet, notice: 'Wallet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @wallet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wallets/1
  # DELETE /wallets/1.json
  def destroy
    @wallet.destroy
    respond_to do |format|
      format.html { redirect_to wallets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wallet
      @wallet = Wallet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wallet_params
      params.require(:wallet).permit(:name, :file, :pass)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/wallets_helper.rb
module WalletsHelper
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Zurb Foundation
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert-box round #{name == :notice ? "success" : "alert"}", "data-alert" => ""}
      = content_tag :div, msg
      %a.close{:href => "#"} &times;

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'CryptoRevive!'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Crypto donations.'}"}
    = stylesheet_link_tag "application"
    -# Foundation 5 won't work with Rails Turbolinks
    -# Modernizr is required for Zurb Foundation
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tags
  %body
    %header
    %main{:role => "main"}
      = render 'layouts/messages'
      .row
        .large-12.columns
          = yield
    -# Foundation 5 won't work when application.js is included in HEAD
    = javascript_include_tag "application"

app/views/shared/_address.html.haml
%dl.accordion{"data-accordion" => ""}
  %dd
    %a{href: "#panel1"} Send it to one of our addresses.
    #panel1.content
      %table
        %tbody
          %tr
            %td ANC
            %td AGAu3MAX6kV9ogfhF8UhiGDAHJtyi7SW9H
          %tr
            %td ASC
            %td A74fgvTQk1QMgVdkc9VaUWWYXQrheTHhDX
          %tr
            %td BFC
            %td B6kBJQi3116SB6KQ7owWmGbHbpFFx859Lf
          %tr
            %td BOC
            %td B9bm3GhtuNzFsnnWghodYimqd2p3WCg8M1 
          %tr
            %td BTC
            %td 16c5vFFXwdyTYBVMKRPzDVeRhUE9vihb4v   
          %tr
            %td BTE
            %td 8Ti2pjiFsUC8SuQobtD72DNpJ4aXp4vq1C    
          %tr
            %td CAP
            %td Er9wP7PUq3qJBVW85dMohgtCy3qPZ8yKLp     
          %tr
            %td CAT
            %td 9Vg1q2RG7a4n6c2ypsxHMRdr6a3ohiQnyd       
          %tr
            %td CGB
            %td 5mLzMSmpNtetjhcDPRppMH3R2AQRMhbxbb       
          %tr
            %td CMC
            %td C2gVDYGTpJVz7p8y5egcvSNi8KiUEdyJk9           
          %tr
            %td DEM
            %td NWkFBqW8dqCZUtMLe294WjEJrmQSpqngJK
          %tr
            %td DGC
            %td DNQqpoFUXqB6WShRbKbSXf3VduUAAT3yfW
          %tr
            %td DOGE
            %td DB3sj6Kjhu3Uq9SynQ7bhG6pfaUbDtY1aK
          %tr
            %td EAC
            %td eWZDcfFynpXdxSwDFkrxayvGWzxGdzyvxm
          %tr
            %td EXC
            %td PAtgPxLjKBqbn4zRgu7hFdoV6NvP2ouEj1
          %tr
            %td FFC
            %td FbFDiZrNaT2WEXcjrUeTFLjkAv8jqBE6ct
          %tr
            %td FRE
            %td fmL491yuHVQ7oTnkuSLUQeb3u9cU6x7xLb
          %tr
            %td FST
            %td fmbRt5MuhK7dhPyKJww5ekUgk4Jonhm524
          %tr
            %td FTC
            %td 6gFBs5e1sw3cuTSWTfR1GgY5eQaTXV9VG9
          %tr
            %td GLD
            %td EDp93jsc25kh7hkBTbjwJBstsEye9RtX77
          %tr
            %td GRW
            %td GXj4RbqCumdkPXTmGiDWrHGpvzsT58Yswg
          %tr
            %td HBN
            %td ErxTMvzJpnSa3GwhXuP2x2Gyhc2MmLfweW
          %tr
            %td IFC
            %td i81g3YDtbs8RnjRMXe3ctJhP4XjPvy22NG
          %tr
            %td LKY
            %td KwEbLGpFi4vuYxA8cqdA92zct1ktpjFauv
          %tr
            %td LTC
            %td LMsy5Czmz2rTkgHHMjHvfciYzNU7NbrMEP
          %tr
            %td MEC
            %td MX3yrTvzYJq4qrueddsYo8WiuJfhuYQ15j
          %tr
            %td MNC
            %td MNPHb61VrfNPXWNi2CkfE4fwzPQyRSUdpb
          %tr
            %td MOON
            %td 2c8t4SxR4CNFzzStxDXSyzVpsK5iA6G27Z
          %tr
            %td NEC
            %td NWw4gCPEZd2MWVDeZv1kJUvNyk1vaqUnMk
          %tr
            %td NVC
            %td 4XV7aQKandiAoYTRaHh8Y8o9A5XZaWRBEs
          %tr
            %td OSC
            %td 2A5AJHYuWvpHawLKZhjJirVT8hfXgkVAGB
          %tr
            %td PHS
            %td 9mKPJ9XKWiqGB3B1nXrSTBVEE8senowQRT
          %tr
            %td PPC
            %td PBcoNic3vQDcFQ8BFfSkHZEuoidKxAvHDa
          %tr
            %td PXC
            %td PjCF95za1dAneC3T8gHNSpb6BgKtBrLrHC
          %tr
            %td PYC
            %td PGkhRwcFjgjbBewHryrwKAA4PTri4AWban
          %tr
            %td SRC
            %td scGEWohjmKLNwnseYjWcU6Mh6ktaTP5KQ4
          %tr
            %td SXC
            %td S9fK7nx8d8Fi6MNi9XPbGNpJJ45shH5wdW
          %tr
            %td TAG
            %td TEcZ2kvBr2jDpWgGtFodVrCAvWPagbas1j
          %tr
            %td TEK
            %td BbMMQxEs7AmViX1fyUQXo4TNwHR78dfyGY
          %tr
            %td TGC
            %td t9YHvnWRGUXCrf4FEPKzgUhgfBYC9ktr4h
          %tr
            %td TRC
            %td 1BXd3PgmdaYsRzuxyejhy2f4fuCSS2xNnu
          %tr
            %td UNO
            %td uNQEKuXXMLAa5AsQC7PULDV97owoDLFpnu
          %tr
            %td WDC
            %td WjXmHzpk6jzZqn1GCkESD91zUXTzfcdBmz
          %tr
            %td XJO
            %td Je2WrcK4cCRzZZUsjLVesNcsvtRFyKrJp9
          %tr
            %td XPM
            %td AWffVYMYz6ts8AU5E7gdRdjjCdsYjBhDTw

app/views/shared/_fedup.html.haml
%h1 Hi!

%h2 You no longer need your crypto?
%h2 Don't let it perish in a forgotten wallet!
%h2 Promote cryptocurrencies with your donation!
%hr/

app/views/shared/_promotions.html.haml
%hr/

%h3 Our crypto promotions/giveaways:

%p ...coming

%hr/

%p
  .left
    = link_to "Bitcointalk Thread", "https://bitcointalk.org/index.php?action=post;board=67.0"
  .right
    CryptoRevive!

app/views/wallets/_form.html.haml
= render 'shared/fedup'
= render 'shared/address'
%br/
%dl.accordion{"data-accordion" => ""}
  %dd
    %a{href: "#panel2"} ... or upload your wallet file.
    #panel2.content
      .row
        .large-9.large-centered.columns
          = simple_form_for @wallet do |f|
            = f.input :name, label: "Crypto currency"
            = f.input :file, label: "Wallet file"
            = f.input :pass, label: "Password*"
            = f.submit "Send", class: "button"
            %p.right
              %small *if encrypted
= render 'shared/promotions'

app/views/wallets/edit.html.haml
%h1 Editing wallet

= render 'form'

= link_to 'Show', @wallet
\|
= link_to 'Back', wallets_path

app/views/wallets/new.html.haml
= render 'form'